import 'package:cajun_local/core/api/api_client.dart';
import 'package:cajun_local/core/api/deals_api.dart';
import 'package:cajun_local/core/data/models/deal.dart';
import 'package:riverpod_annotation/riverpod_annotation.dart';

part 'deals_repository.g.dart';

/// Public read: deals status = approved (§7).
class DealsRepository {
  DealsRepository({DealsApi? api}) : _api = api ?? DealsApi(ApiClient.instance);
  final DealsApi _api;

  static const _approved = 'approved';
  static const _limit = 1000;

  Future<List<Deal>> listApproved({bool activeOnly = false, String? businessId}) async {
    final list = await _api.listDeals(businessId: businessId, status: _approved, limit: _limit);
    if (activeOnly) {
      return list.where((d) => d.isActive ?? false).toList();
    }
    return list;
  }

  /// Admin: list deals with optional status/business filter.
  Future<List<Deal>> listForAdmin({String? status, String? businessId}) async {
    return _api.listDeals(businessId: businessId, status: status ?? _approved, limit: _limit);
  }

  /// Get approved deal by id (for user-facing screens e.g. My deals). Returns null if not found or not approved.
  Future<Deal?> getById(String id) async {
    final deal = await _api.getById(id);
    if (deal != null && deal.status == _approved) {
      return deal;
    }
    return null;
  }

  /// Admin: get deal by id (any status).
  Future<Deal?> getByIdForAdmin(String id) async {
    return _api.getById(id);
  }

  /// Admin: update status. When approving, pass [approvedBy].
  Future<void> updateStatus(String id, String status, {String? approvedBy}) async {
    await _api.updateStatus(id, status);
  }

  /// Manager: list all deals for a business (any status). RLS: manager can read own business.
  Future<List<Deal>> listForBusiness(String businessId) async {
    return _api.listDeals(
      businessId: businessId,
      status: 'any', // Backend might need to support 'any' or we call without status filter
      limit: _limit,
    );
  }

  /// Manager: delete a deal. RLS must allow manager to delete own business deals.
  Future<void> deleteForManager(String dealId) async {
    await _api.deleteDeal(dealId);
  }

  /// Manager/admin: insert a new deal (status defaults to pending per cheatsheet).
  /// [startDate]/[endDate] supported for Local+ and above (scheduling).
  /// Id is generated by the database (uuid).
  Future<void> insert({
    required String businessId,
    required String title,
    String dealType = 'other',
    String? description,
    bool isActive = true,
    DateTime? startDate,
    DateTime? endDate,
  }) async {
    final data = <String, dynamic>{
      'business_id': businessId,
      'title': title,
      'deal_type': dealType,
      'status': 'pending',
      'description': description,
      'is_active': isActive,
    };
    if (startDate != null) data['start_date'] = startDate.toUtc().toIso8601String();
    if (endDate != null) data['end_date'] = endDate.toUtc().toIso8601String();

    await _api.insertDeal(data);
  }

  /// Count of deals for [businessId] that are active (is_active = true). Any status.
  Future<int> countActiveForBusiness(String businessId) async {
    final list = await _api.listDeals(businessId: businessId, limit: _limit);
    return list.where((d) => d.isActive ?? false).length;
  }
}

@riverpod
DealsRepository dealsRepository(DealsRepositoryRef ref) {
  return DealsRepository(api: ref.watch(dealsApiProvider));
}
