export 'package:cajun_local/core/data/repositories/favorites_repository.dart';
export 'package:cajun_local/core/data/repositories/user_plans_repository.dart';
export 'package:cajun_local/core/data/repositories/user_subscriptions_repository.dart';
export 'package:cajun_local/core/data/repositories/business_repository.dart';
export 'package:cajun_local/core/data/repositories/business_images_repository.dart';
export 'package:cajun_local/core/data/repositories/business_subscriptions_repository.dart';
export 'package:cajun_local/core/data/repositories/reviews_repository.dart';
export 'package:cajun_local/core/data/repositories/business_claims_repository.dart';
export 'package:cajun_local/core/data/repositories/user_deals_repository.dart';
export 'package:cajun_local/core/data/repositories/user_punch_cards_repository.dart';
export 'package:cajun_local/core/data/repositories/event_rsvps_repository.dart';
export 'package:cajun_local/core/data/repositories/profiles_repository.dart';

import 'package:cajun_local/core/data/repositories/user_plans_repository.dart';
import 'package:cajun_local/core/data/repositories/user_subscriptions_repository.dart';
import 'package:cajun_local/core/data/repositories/business_subscriptions_repository.dart';

import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:cajun_local/core/data/listing_data_source.dart';
import 'package:cajun_local/core/subscription/user_tier_service.dart';
import 'package:cajun_local/core/revenuecat/revenuecat_service.dart';
import 'package:cajun_local/core/subscription/business_tier_service.dart';
import 'package:cajun_local/core/data/services/app_storage_service.dart';

final listingDataSourceProvider = Provider<ListingDataSource>((ref) {
  return ListingDataSource(ref: ref);
});

final userTierServiceProvider = Provider<UserTierService>((ref) {
  final subscriptionsRepository = ref.watch(userSubscriptionsRepositoryProvider);
  final plansRepository = ref.watch(userPlansRepositoryProvider);
  return UserTierService(subscriptionsRepository: subscriptionsRepository, plansRepository: plansRepository);
});

final appDataScopeProvider = Provider<ListingDataSource>((ref) {
  return ref.watch(listingDataSourceProvider);
});

final revenueCatServiceProvider = Provider<RevenueCatService?>((ref) {
  return null;
});

// Note: Repository providers (e.g. favoritesRepositoryProvider, reviewsRepositoryProvider)
// are now auto-generated by @riverpod in their respective files.
// Check core/data/repositories/* for @riverpod annotations.

final businessTierServiceProvider = Provider<BusinessTierService>((ref) {
  final subscriptionsRepository = ref.watch(businessSubscriptionsRepositoryProvider);
  return BusinessTierService(subscriptionsRepository: subscriptionsRepository);
});

final appStorageServiceProvider = Provider<AppStorageService>((ref) {
  return AppStorageService();
});
