export 'package:cajun_local/features/favorites/data/repositories/favorites_repository.dart';
export 'package:cajun_local/features/profile/data/repositories/user_plans_repository.dart';
export 'package:cajun_local/features/profile/data/repositories/user_subscriptions_repository.dart';
export 'package:cajun_local/features/businesses/data/repositories/business_repository.dart';
export 'package:cajun_local/features/businesses/data/repositories/business_images_repository.dart';
export 'package:cajun_local/features/businesses/data/repositories/business_subscriptions_repository.dart';
export 'package:cajun_local/features/reviews/data/repositories/reviews_repository.dart';
export 'package:cajun_local/features/businesses/data/repositories/business_claims_repository.dart';
export 'package:cajun_local/features/deals/data/repositories/user_deals_repository.dart';
export 'package:cajun_local/features/profile/data/repositories/user_punch_cards_repository.dart';
export 'package:cajun_local/features/events/data/repositories/event_rsvps_repository.dart';
export 'package:cajun_local/features/profile/data/repositories/profiles_repository.dart';

import 'package:cajun_local/features/profile/data/repositories/user_plans_repository.dart';
import 'package:cajun_local/features/profile/data/repositories/user_subscriptions_repository.dart';
import 'package:cajun_local/features/businesses/data/repositories/business_subscriptions_repository.dart';
import 'package:cajun_local/features/auth/presentation/controllers/auth_controller.dart';

import 'package:cajun_local/core/subscription/user_tier_service.dart';
import 'package:cajun_local/core/subscription/resolved_permissions.dart';
import 'package:cajun_local/core/revenuecat/revenuecat_service.dart';
import 'package:cajun_local/core/subscription/business_tier_service.dart';
import 'package:cajun_local/core/data/services/app_storage_service.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

final userTierServiceProvider = Provider<UserTierService>((ref) {
  final subscriptionsRepository = ref.watch(userSubscriptionsRepositoryProvider);
  final plansRepository = ref.watch(userPlansRepositoryProvider);
  final service = UserTierService(subscriptionsRepository: subscriptionsRepository, plansRepository: plansRepository);

  // Watch userId to trigger refresh on auth changes
  final userId = ref.watch(authControllerProvider).valueOrNull?.id;
  service.refresh(userId);

  return service;
});

final userPermissionsProvider = StateProvider<ResolvedPermissions>((ref) {
  final service = ref.watch(userTierServiceProvider);
  // Initial value
  return service.value ?? ResolvedPermissions.free;
});

final revenueCatServiceProvider = Provider<RevenueCatService?>((ref) {
  return null;
});

// Note: Repository providers (e.g. favoritesRepositoryProvider, reviewsRepositoryProvider)
// are now auto-generated by @riverpod in their respective files.
// Check core/data/repositories/* for @riverpod annotations.

final businessTierServiceProvider = Provider<BusinessTierService>((ref) {
  final subscriptionsRepository = ref.watch(businessSubscriptionsRepositoryProvider);
  return BusinessTierService(subscriptionsRepository: subscriptionsRepository);
});

final appStorageServiceProvider = Provider<AppStorageService>((ref) {
  return AppStorageService();
});
