// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFYmeuDAB8wKRgN2bevk48rWMY1KWrOUU',
    appId: '1:791192605612:android:8c84840541feef7625a009',
    messagingSenderId: '791192605612',
    projectId: 'cajun-local',
    storageBucket: 'cajun-local.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCT1in747jSEfE2aYE07gyYcsZ-tJfz8jk',
    appId: '1:791192605612:ios:261efe2227a72f3025a009',
    messagingSenderId: '791192605612',
    projectId: 'cajun-local',
    storageBucket: 'cajun-local.firebasestorage.app',
    iosClientId: '791192605612-ivlhg3b4bqr1kl2fv5d1h51nrp41l7rm.apps.googleusercontent.com',
    iosBundleId: 'com.sitesnapps.cajunlocal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCT1in747jSEfE2aYE07gyYcsZ-tJfz8jk',
    appId: '1:791192605612:ios:261efe2227a72f3025a009',
    messagingSenderId: '791192605612',
    projectId: 'cajun-local',
    storageBucket: 'cajun-local.firebasestorage.app',
    iosClientId: '791192605612-ivlhg3b4bqr1kl2fv5d1h51nrp41l7rm.apps.googleusercontent.com',
    iosBundleId: 'com.sitesnapps.cajunlocal',
  );

}